name: 'Setup and install'
description: 'Common setup steps for Actions'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        cache-dependency-path: '**/pnpm-lock.yaml'

    - shell: bash
      run: pnpm add -g turbo

    - shell: bash
      run: pnpm install
